config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
  }
  root 'profile#show'
  resources :missions, only: [:show]
  post 'result' => "missions#result"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mission.rb
# == Schema Information
#
# Table name: missions
#
#  id          :bigint           not null, primary key
#  title       :string
#  enabled     :boolean          default(FALSE)
#  user_id     :bigint
#  instruction :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Mission < ApplicationRecord

  has_many :group_missions
  has_many :groups, through: :group_missions

  has_many :results
  has_many :users, through: :results

  belongs_to :user

  has_many :mission_modul_questions
  has_many :modul_questions, through: :mission_modul_questions

  rails_admin do
    exclude_fields :group_missions, :groups, :results,
                   :users, :mission_modul_questions, :modul_questions
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def show
    @mission = Mission.find(params["id"])
    @modul_questions = @mission.modul_questions
    if Result.find_by(user_id: current_user.id, mission_id: @mission.id).present?
      redirect_to root_path
    else
      @result = Result.create(user_id: current_user.id, mission_id: @mission.id)

    end
  end

  def result
    question = Question.find(params["type"])
    if question.right_answer.present?
      question.right_answer == params["answer"]
    end
  end

end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/show.html.erb
  <%=  render partial: "blocks/header"  %>
    <section class=" text-center container">
      <div class="py-lg">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light"><%= @mission.title %></h1>
          <p class="lead text-muted"><%= @mission.instruction %></p>
        </div>
      </div>
    </section>
    <% @number_modul = 0 %>

    <%  @modul_questions.each do |modul_question| %>
        <%  @number_modul = @number_modul +1 %>

          <div class="r py-lg">
            <div class="col-lg-6 col-md-8 mx-auto">
              <h1 class="fw-light">Модуль <%=@number_modul%>. <%= modul_question.title %></h1>
              <p class="lead text-muted"><%= modul_question.instruction %></p>
            </div>
          </div>

        <% @number_question = 0 %>
        <%  modul_question.questions.each do |question| %>
            <% @number_question = @number_question +1 %>

                <div class="d-flex gap-5 justify-content-center">
                     <div class="list-group mx-0 w-50">
                       <%= form_with url: result_path do |f| %>
                           <% if  question.type_question == "Закрытой формы"  %>
                            <span>
                              <input type="hidden" name="type_question" value= <%= question.type_question %>>
                              <input type="hidden" name="question_id" value= <%= question.id %>>
                             <%= question.value %>
                              <small class="d-block text-muted">Выберите один правильный ответ</small>
                            </span>
                            <%  question.answers.each do |answer| %>
                                <div class="list-group-item d-flex gap-2">

                                <%= f.radio_button :answer, answer.id %>
                                <%= f.label  answer.value %>
                                 </div>
                            <% end %>

                           <% elsif question.type_question == "Открытой формы"%>
                           <span>
                             <%= question.value %>
                             <small class="d-block text-muted">Дайте развернутый ответ</small>
                            </span>

                            <div class="list-group-item d-flex gap-2">
                              <%= f.text_field :answer %>
                              <%= f.label  "Подробно опишите ваш ответ" %>
                              <input type="hidden" name="type_question" value= <%= question.type_question %>>
                              <input type="hidden" name="question_id" value= <%= question.id %>>
                             </div>
                             <% elsif question.type_question == "Закрытой формы >1"%>








                           <span>
                              <input type="hidden" name="type_question" value= <%= question.type_question %>>
                              <input type="hidden" name="question_id" value= <%= question.id %>>

                             <%= question.value %>
                             <small class="d-block text-muted">Выберите несколько правильных ответов</small>
                            </span>
                           <%  question.answers.each do |answer| %>
                             <div class="list-group-item d-flex gap-2">
                               <input type="hidden" name="" value= <%= question.type_question %>>
                               <%= f.check_box  answer.id %>
                               <%= f.label  answer.value %>
                             </div>
                           <% end %>










                           <% end %>



                         <div class="actions">
                           <%= f.submit "Ответить", :class=>"btn btn-primary btn-lg px-4 me-sm-3" %>
                         </div>
                       <% end %>

                     </div>
                </div>

            <% end %>

    <% end %>